[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p data/uploads"]

[start]
cmd = "uvicorn src.app.main:server --host 0.0.0.0 --port $PORT"
